Repository kubesphere-sigs/ks-releaser, pull requests merged in 2021-12, with the labels that each got.

#50 Use trivy to scan container image
  .github/workflows/build.yaml
Labels: size/S, lgtm, chore

#51 Add linuxsuren as an owner, JohnNiang as a reviewer
  OWNERS
Labels: size/XS, lgtm, no-changelog

#48 Fix incorrect indent for yaml code block
  README.md
Labels: size/S, lgtm, no-changelog, approved

#56 Add Tekton manifests
  .github/tekton/README.md
  .github/tekton/build-bot.yaml
  .github/tekton/pull-request-pipeline.yaml
  .github/tekton/pull-request-trigger-template.yaml
  .github/tekton/pull-request-trigger.yaml
  .github/tekton/shared-storage.yaml
  .github/workflows/build.yaml
Labels: size/L, lgtm, approved

#57 Reduce length of pipeline run name
  .github/tekton/pull-request-trigger-template.yaml
Labels: size/XS, lgtm, approved
